Dockerfile.unstable

Creating a Dockerfile for a locally-installed package (not based on a version published to pypi).

Adding dockerfile that will install the local bartender

---

bartender/__init__.py
bartender/__main__.py
test/bartender_test.py

This addresses beer-garden/beer-garden#38

Checking for connection to rabbit message interface on startup

---

bartender/monitor.py
bartender/pika.py
bartender/thrift/handler.py
test/monitor_test.py
test/thrift/handler_test.py

This fixes beer-garden/beer-garden#37

Publisher confirms

---

bartender/request_validator.py
requirements.in
requirements.txt
setup.py

Fixes beer-garden/beer-garden#54

Using `str` method from the `futures` package to correctly handle unicode

---

bartender/__init__.py
test/bartender_test.py

This fixes beer-garden/beer-garden#65

Being stricter about the exceptions allowed when connection to brew-view

---

bartender/__main__.py

This is part of the solution for beer-garden/beer-garden#139

Adding timeout to brew-view connection startup check

---

bartender/thrift/handler.py

This is part of beer-garden/beer-garden#140

 Passing AMQ connection parameters to plugins

---

bartender/app.py

Part of beer-garden/beer-garden#140

Bg-utils PikaClient moved, using Bartender's child class

---

bartender/__main__.py

Fixes beer-garden/beer-garden#160

Moving brew-view check before mongo check to fix race condition

---

.travis.yml
Makefile
test/local_plugins/env_help_test.py

This fixes beer-garden/beer-garden#178

Updating travis configuration

---

bin/app.sh
dev_conf/config.yaml

This is part of beer-garden/beer-garden#226

Renaming dev config file to .yaml

---

dev_conf/config.yaml

Goes along with the brew-view auth_update PR.

Changing defaults to match brew-view

---

bartender/app.py
test/app_test.py

This fixes beer-garden/beer-garden#245

Mongo pruner time between runs can now be a float

---

bartender/app.py

This fixes beer-garden/beer-garden#244.

Now only parent requests are removed by the MongoPruner

---

bartender/thrift/handler.py
requirements.txt
test/thrift/handler_test.py

Part of beer-garden/beer-garden#305.

Publishing now raises on errors instead of returning false

---

bartender/request_validator.py
test/request_validator_test.py

This fixes a `DeprecationWarning`.

Importing from collections.abc to fix DeprecationWarning

---

bartender/app.py
bartender/instances.py
bartender/local_plugins/registry.py
bartender/queues.py
bartender/requests.py
bartender/systems.py
bartender/thrift/handler.py
test/requests_test.py

This PR is the first part of moving functionality into bartender.

Thrift refactor

---

bartender/local_plugins/plugin_runner.py
test/local_plugins/plugin_runner_test.py

This fixes beer-garden/beer-garden#317

Local plugins always log using the unformatted logger

---

bartender/thrift/handler.py

This fixes beer-garden/beer-garden#350.

Removing auto-delete flag from admin queues

---

bartender/thrift/handler.py
test/thrift/handler_test.py

This fixes beer-garden/beer-garden#352.

Specifying persistent delivery mode when publishing to pika

---

bartender/local_plugins/env_help.py
bartender/mongo_pruner.py
test/mongo_pruner_test.py

Reverts beer-garden/bartender#107

Revert "Remove Caching from Pruner"

---

bartender/local_plugins/plugin_runner.py
bartender/specification.py
dev_conf/config.yaml

Fixes beer-garden/beer-garden#774.

Switching host_env_vars to be optional instead of empty array default
